name: Run scraper commit back data

on:
  push:
    branches:
      - master

  schedule: # every hour
    - cron:  '*/5 * * * *'

jobs:
  execute_notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.7.7
          poetry_version: 1.0.5
          working_directory: .
          args: install

      - name: execute scraper
        run: |
            python scripts/01_download.py
            
      - name: commit files 
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data/raw/.
            git commit -m "Update data (GitHub Action)"

      - name: Push to repo
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
